spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jenkins_db?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:/mybatis/*.xml